package com.saubh.solveitai.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLightMediumContrast = Color(0xFF003A57)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF0074A8)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF4D0094)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF8C41E9)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF003E38)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF007B70)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF6FAFF)
val onBackgroundLightMediumContrast = Color(0xFF171C21)
val surfaceLightMediumContrast = Color(0xFFF6FAFF)
val onSurfaceLightMediumContrast = Color(0xFF0C1216)
val surfaceVariantLightMediumContrast = Color(0xFFD9E4EF)
val onSurfaceVariantLightMediumContrast = Color(0xFF2D3740)
val outlineLightMediumContrast = Color(0xFF49545D)
val outlineVariantLightMediumContrast = Color(0xFF646E78)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2C3136)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF1F8)
val inversePrimaryLightMediumContrast = Color(0xFF8BCEFF)
val surfaceDimLightMediumContrast = Color(0xFFC2C7CD)
val surfaceBrightLightMediumContrast = Color(0xFFF6FAFF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF4FB)
val surfaceContainerLightMediumContrast = Color(0xFFE4E9EF)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DDE4)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD2D8)

val primaryDarkMediumContrast = Color(0xFFBDE1FF)
val onPrimaryDarkMediumContrast = Color(0xFF00283E)
val primaryContainerDarkMediumContrast = Color(0xFF00B2FF)
val onPrimaryContainerDarkMediumContrast = Color(0xFF002032)
val secondaryDarkMediumContrast = Color(0xFFE9D4FF)
val onSecondaryDarkMediumContrast = Color(0xFF37006C)
val secondaryContainerDarkMediumContrast = Color(0xFFAE71FF)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFF5CF3E1)
val onTertiaryDarkMediumContrast = Color(0xFF002B27)
val tertiaryContainerDarkMediumContrast = Color(0xFF00C4B4)
val onTertiaryContainerDarkMediumContrast = Color(0xFF002925)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F1418)
val onBackgroundDarkMediumContrast = Color(0xFFDEE3E9)
val surfaceDarkMediumContrast = Color(0xFF0F1418)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3E4851)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD3DEE9)
val outlineDarkMediumContrast = Color(0xFFA9B3BE)
val outlineVariantDarkMediumContrast = Color(0xFF87929C)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B30)
val inversePrimaryDarkMediumContrast = Color(0xFF004D71)
val surfaceDimDarkMediumContrast = Color(0xFF0F1418)
val surfaceBrightDarkMediumContrast = Color(0xFF40454A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF04080C)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191E23)
val surfaceContainerDarkMediumContrast = Color(0xFF23282D)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2E3338)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF393E43)







